### PR TITLE
Polish comments of fields

### PR DESCRIPTION
**Pull request by fred-apex-ai**
@wjwwood This is just a minor refinement of message comments. Let me know if I should bump the version number.

### CODE REVIEW

**Comment by wjwwood** [comment]
@fred-apex-ai You'll have to ask the maintainer of this package. I don't have any involvement on it.

**Comment by fred-apex-ai** [comment]
@SteveMacenski Please review. This is just a minor refinement of message comments. Let me know if I should bump the version number.

**Review by SteveMacenski — APPROVED** [review]
Yes, please increment the version number and I'll run a release over it after merging. 

Sorry for the delay, I was on a beach :beach_umbrella:

**Comment by fred-apex-ai** [comment]
@SteveMacenski Sorry for the delay, I was on vacation right when you came back and the got sick. I bumped the minor version and updated the PR

**Review by SteveMacenski — APPROVED** [review]

**Pull request merged**
